### ISSUE TITLE
No "waldorf" binary in the node_modules folder

### ISSUE THREAD

**Issue by MartinDelille** [hobbyquaker/waldorf#1]
I installed waldorf with the following command line (I don't need `sudo` to install npm packages):

    npm install -g waldorf

Unfortunately, `waldorf` is not in the path:

    $ waldorf
    zsh: command not found: waldorf

I tried to look for the waldorf binary, but the `node_modules/waldorf` folder doesn't contains `bin` folder (like `gulp` for examples):

    $ ls -l /usr/local/lib/node_modules/waldorf/
    total 72
    -rw-r--r--    1 martin  admin    592 Mar 23  2017 Gulpfile.js
    -rw-r--r--    1 martin  admin   6406 Mar 23  2017 README.md
    -rw-r--r--    1 martin  admin    850 Mar 22  2017 config.js
    drwxr-xr-x    5 martin  admin    170 Mar  6 11:44 docs
    -rwxr-xr-x    1 martin  admin  12330 Mar 23  2017 index.js
    drwxr-xr-x  157 martin  admin   5338 Mar  6 11:44 node_modules
    -rw-r--r--    1 martin  admin   2457 Mar  6 11:44 package.json

I am missing something?

**Comment by hobbyquaker** [comment]
Oh, my fault, forgot to set the `bin` attribute in package.json 
Fixed with v1.0.2 - you should have `/usr/local/bin/waldorf` after installing.
If you're installing without superuser rights that link can't be created - but you can also just execute the `index.js` file.
